add `generate_manifest.py` script
neurodatascience/mr_proc-ppmi pull request #2
Opened 2023-03-23 02:08 UTC by michellewang

Usage:
```
usage: generate_manifest.py [-h] --global_config GLOBAL_CONFIG
                            [--imaging_filename IMAGING_FILENAME]
                            [--tabular_filename TABULAR_FILENAME] [--overwrite]

Script to generate manifest file for PPMI dataset. Requires an imaging data availability
info file that can be downloaded from the LONI IDA, as well as the PPMI tabular data
availability info file. Both files should be in [DATASET_ROOT]/tabular/study_data.

optional arguments:
  -h, --help            show this help message and exit
  --global_config GLOBAL_CONFIG
                        path to global config file for your mr_proc dataset (required)
  --imaging_filename IMAGING_FILENAME
                        name of file containing imaging data availability info, with
                        columns "Subject ID", "Visit", and "Modality" (default:
                        idaSearch.csv)
  --tabular_filename TABULAR_FILENAME
                        name of file containing tabular data availability info, with
                        columns "PATNO" and "EVENT_ID" (default: Age_at_visit.csv)
  --overwrite           overwrite any existing mr_proc_manifest.csv file
```

New manifest file has been added to `/data/pd/ppmi/tabular/mr_proc_manifest.csv` (on BIC).

**Note**: When I ran the script, there were 34 imaging visits (out of 2643) that had no matching entry in the age dataframe, which is unexpected, so `Age_at_visit.csv` might not be the best file to check for tabular data availability.

Closes #1.

2023-03-23 02:39 UTC, michellewang commented
I just realized that the `anat`/`func` differentiation cannot be based on the `Modality` column in the LONI file, because some fMRI entries also have `Modality=MRI`... Will try to figure out another way to get the availability.

2023-04-03 15:12 UTC, michellewang commented
Added a `filter_image_descriptions.py` script to generate lists of description strings for each datatype (`anat`, `dwi`, `func`, and also `t1`/`t2`/`flair` since that should be useful for HeuDiConv). 

The datatype-to-description mapping is saved in `ppmi_imaging_descriptions.json` (and is used to generate the manifest), and the descriptions that were dropped (because they didn't correspond to any datatype, were 2D, etc.) are listed in `ppmi_imaging_ignored.csv`. @nikhil153 could you take a look when you have the time to see if these are good?

`/data/pd/ppmi/tabular/mr_proc_manifest.csv` on BIC has also been updated.

2023-04-05 15:02 UTC, michellewang commented
I have added all motor/non-motor assessment files (instead of just the `Age_at_visit` file) to check for tabular data availability, but there are still 13 imaging visits that don't have corresponding tabular data entries. That number becomes 14 if we only check `Age_at_visit.csv`, the 5 UPDRS files, and MoCA.

2023-05-10 21:25 UTC, michellewang commented
More changes:

2023-05-10 21:31 UTC, michellewang commented
More changes after discussions with Nikhil:
1. The manifest now only has 4 columns: `participant_id`, `visit`, `session`, `datatype`
2. The default behaviour is to append new rows to the existing manifest
3. We do a sanity check to make sure that all subject-session pairs from the existing manifest are still valid (i.e., no subject ID change, no deleted subjects)
4. The `--regenerate` flag can be used to create a new manifest that ignores content of any existing manifest. This should be used if we want to modify existing rows in the manifest
5. All manifests are stored in a backup directory: `mr_proc_manifest.csv` is a symlink to the newest file in the backup directory
6. The `--make_release` flag can be used to create a backup of the `<DATASET_ROOT>/tabular` directory in `<DATASET_ROOT>/releases`. This only copies a subset of the PPMI study files (those needed to generate the manifest), because otherwise the release directory is too large (>4Gb)

2023-05-18 14:48 UTC, nikhil153 requested changes

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_PHANTOM",
Don't need `phantoms`

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_phantom",
Don't need `phantoms`

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_GATED",
Check with @bcmcpher if these have substantial differences - if so we need to encode those in `acq-` label. 

`DTI_FA` seems to be mislabeled phantoms as well - unless they meant to capture a solar eclipse. 
see Subject ID: `100006`, Image ID: `I1526385`

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_RL_FA",
This seems to be mislabeled as `MRI` modality instead of `DTI`!

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "Repeat DTI_non gated",
If `REPEAT` implies multiple runs for the same subject, then need to check with @bcmcpher to see which one we select for BIDS / downstream conversion.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "eReg - DT_SSh_iso SENSE",
`SENESE` seems to have very different contrast - check with @bcmcpher if this needs to be encoded in the `acq-` BIDS label

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +    "func": [
Sadly I have no idea about fmri... We should check with someone else before BIDS conversion.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "COR",
Coronal acq. Looks bad..

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +    "t1": [
We should label the acq-plane in the BIDS naming for these. 
Most axial scans will have high slice thickness (2.0mm) which will play a role downstream

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "MRI BRAIN WO IVCON",
This looks like T2w

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "T!",
LoL

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "ax t1 reformat",
Not a 3D scan

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "AX PD + T2",
This will need parsing or acq-params to label PD vs T2 correctly in BIDS.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "AXIAL_T2_STAR",
I believe this has a different suffix in BIDS.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "Ax T2* GRE",
I believe this has a different suffix in BIDS.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "t2_tirm_tra_dark-fluid_",
Not sure what these are... might be FLAIR. 
They have very few slices. So probably not useful.

2023-05-18 14:48 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +    "anat": [
Why is `anat` separate category?

2023-05-18 15:00 UTC, michellewang commented on tabular/generate_manifest.py
> +GROUPS_KEEP = ['Parkinson\'s Disease', 'Prodromal', 'Healthy Control', 'SWEDD', 'GenReg Unaff']
Some of the already-processed subjects on BIC are `SWEDD` or `GenReg Unaff`, and we wanted everyone to be in the manifest. The other option was to remove anyone who isn't PD/Control/Prodromal from BIC, which is probably better but more involved

2023-05-18 15:09 UTC, michellewang commented on tabular/ppmi_imaging_ignored.csv
> +sag
Image ID `440670` (only 16 slices in sagittal plane)

2023-05-18 15:17 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +    "anat": [
In the manifest we only care about `anat`/`dwi`/`func` so this just combines all the anatomical image subtypes into a single list to check

2023-05-18 19:56 UTC, michellewang commented on tabular/generate_manifest.py
> +GROUPS_KEEP = ['Parkinson\'s Disease', 'Prodromal', 'Healthy Control', 'SWEDD', 'GenReg Unaff']
Dropped `GenReg Unaff` (only 1 subject), keeping `SWEDD`

2023-05-18 20:00 UTC, michellewang commented on tabular/generate_manifest.py
> +        '--tabular_filenames', type=str, nargs='+', default=DEFAULT_TABULAR_FILENAMES,
Removing this option

2023-05-18 20:02 UTC, michellewang commented on tabular/filter_image_descriptions.py
> +EXCLUDE_IN_ANAT_T1 = EXCLUDE_IN_ANAT + ['Ax 3D SWAN GRE straight']
Because `EXCLUDE_IN_ANAT` is re-used for the `exclude_in` parameter for `T2` and `FLAIR` also

2023-05-18 20:02 UTC, michellewang commented on tabular/ppmi_imaging_ignored.csv
> +SAG FSPGR 3D
Keeping `SAG FSPGR 3D` after checking with Nikhil

2023-05-18 20:05 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +    "dwi": [
Adding a note here that for the phantom scans we'll rely on the number of slices in `heuristic.py` during BIDS conversion with Heudiconv

2023-05-18 20:12 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_PHANTOM",
Dropped `DTI_PHANTOM`

2023-05-18 20:12 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "DTI_phantom",
Dropped `DTI_phantom`

2023-05-18 20:17 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "COR",
Dropped. Also dropping `SAG` and `TRA` which have similar low quality (55 slices)

2023-05-18 20:17 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +    "t1": [
TODO in `heuristic.py`

2023-05-18 20:23 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "MRI BRAIN WO IVCON",
Moved to T2

2023-05-18 20:25 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "ax t1 reformat",
Dropped `ax t1 reformat`

2023-05-18 20:48 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "Ax T2* GRE",
Took another look and this one is actually 2D (34 slices), dropping

2023-05-19 01:08 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "t2_tirm_tra_dark-fluid_",
For this do you mean all 3 or just `t2_tirm_tra_dark-fluid_` and/or `t2_tirm_tra_dark-fluid NO BLADE`? Just making sure because I think GitHub sometimes shows surrounding lines

2023-05-19 01:55 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "AXIAL_T2_STAR",
Moved to `t2_star` instead of `t2`

2023-05-19 01:55 UTC, michellewang commented on tabular/ppmi_imaging_descriptions.json
> +        "Ax T2* GRE",
Moved to `t2_star` instead of `t2`

2023-05-19 02:02 UTC, michellewang commented on tabular/ppmi_imaging_ignored.csv
> +Description
I added the neuromelanin descriptions under T2 (i.e. in the same list as the other T2 descriptions)

2023-05-19 03:27 UTC, nikhil153 commented on tabular/ppmi_imaging_descriptions.json
> +        "t2_tirm_tra_dark-fluid_",
So `t2 weighted double echo` has both proton density (PD) and T2 - which needs to be split with additional criteria in the heuristics. 
The other two look more FLAIR-like than PD + they have "dark-fluid" in the description, so they are likely to be FLAIR. 
All three have much fewer slices than the more recent scans especially the sagittal acq. 
For now let's download these but not include in the initial "strict" heuristics criteria.

2023-06-08 18:06 UTC, nikhil153 approved these changes

2023-06-08 18:06 UTC, nikhil153 commented on tabular/generate_manifest.py
> +}
Would it make sense to keep them external to this code - they likely to be used by many analysis downstream, no?

2023-06-08 18:06 UTC, nikhil153 commented on tabular/generate_manifest.py
> +}
Same as above comment: move to external config?

2023-06-08 18:28 UTC, michellewang commented on tabular/filters.py
> +SUFFIX_T2_STAR = 'T1starw'
Yes! Thanks for catching it

2023-06-08 18:32 UTC, michellewang commented on tabular/filter_image_descriptions.py
> +def get_all_descriptions(descriptions_dict, verbose=False):
Because it's a recursive function and I didn't want to expose the `descriptions` accumulator to outside (since it should always be `[]` when first called and gets populated by the function itself)

2023-06-08 18:38 UTC, michellewang commented on tabular/generate_manifest.py
> +}
Good point, we could put them in say `tabular/ppmi_constants.py`. I think we should make another PR though because it'll require some refactoring of files in #16.

2023-06-08 20:12 UTC, merged